defaults:
  - dataset: mnist
  - resources: cpu
  - reproducibility: default
  - data_loading: torch
  - experiment: default
  - _self_

experiment:
  exp_name: mlprandom
  model_selection_training_runs: 2

random:
  defaults:
    - optimizer: random_adam
    - search/random_mlp@_here_
    - _self_
  budget: 5
  model: mlwiz.model.MLP
  checkpoint: true
  shuffle: true
  batch_size: 512
  epochs: 2
  dim_embedding: 5
  mlwiz_tests: true
