# Telegram Bot
# telegram_config_file: telegram_config.yml


# Dataset and Splits
data_root: DATA
dataset_class: mlwiz.data.dataset.MNIST
data_splits_file:  examples/DATA_SPLITS/MNIST/MNIST_outer3_inner2.splits


# Hardware
device:  cpu
max_cpus:  8
max_gpus: 1
gpus_per_task:  1
# gpus_subset: 0,1,2,3,4,5,6,7,8


# Data Loading
dataset_getter: mlwiz.data.provider.DataProvider
data_loader:
  class_name: torch.utils.data.DataLoader
  args:
    num_workers : 0
    pin_memory: False


# Reproducibility
seed: 42


# Experiment
result_folder: RESULTS
exp_name: cnn
experiment: mlwiz.experiment.Experiment
higher_results_are_better: True
evaluate_every: 1
risk_assessment_training_runs: 3


grid:
  model: mlwiz.model.CNN
  checkpoint: True
  shuffle: True
  batch_size: 512
  epochs: 2

  # Model specific arguments #

  # ------------------------ #

  # Optimizer (with an example - 3 possible alternatives)
  optimizer:
    - class_name: mlwiz.training.callback.optimizer.Optimizer
      args:
        optimizer_class_name: torch.optim.Adam
        lr:
          - 0.01
        weight_decay: 0.

  # Scheduler (optional)
  scheduler: null

  # Loss metric (with an example of Additive Loss)
  loss: mlwiz.training.callback.metric.MulticlassClassification

  # Score metric (with an example of Multi Score)
  scorer:
    - class_name: mlwiz.training.callback.metric.MultiScore
      args:
        main_scorer: mlwiz.training.callback.metric.MulticlassAccuracy

  # Readout (optional)
  readout: mlwiz.model.readout.graph_readout.LinearGraphReadout

  # Training engine
  engine:
    - class_name: mlwiz.training.engine.TrainingEngine
      args:
        eval_training:  # whether to re-compute epoch loss/scores after training or use those obtained while the model is being trained with mini-batches
          - False  # default behavior, saves some compute time as we are generally interested in validation scores
      
  # Gradient clipper (optional)
  gradient_clipper: null

  # Early stopper (optional, with an example of "patience" early stopping on the validation score)
  early_stopper:
    - class_name:
        - mlwiz.training.callback.early_stopping.PatienceEarlyStopper
      args:
        patience:
          - 10
        # SYNTAX: (train_,validation_)[name_of_the_scorer_or_loss_to_monitor] -> we can use MAIN_LOSS or MAIN_SCORE
        monitor: validation_main_score
        mode: max  # is best the `max` or the `min` value we are monitoring?
        checkpoint: True  # store the best checkpoint

  # Plotter of metrics
  plotter:
    - class_name: mlwiz.training.callback.plotter.Plotter
      args:
        store_on_disk: True