defaults:
  - dataset: mnist_inner5
  - resources: cpu
  - reproducibility: default
  - data_loading: torch
  - experiment: default
  - _self_

experiment:
  exp_name: mlp
  model_selection_training_runs: 2
  training_timeout_seconds: 20

grid:
  defaults:
    - optimizer:
        - adam
        - adagrad
    - search/mlp@_here_
    - _self_
  model: mlwiz.model.MLP
  checkpoint: true
  shuffle: true
  batch_size: 512
  epochs: 400
  dim_embedding: 5
  mlwiz_tests: true
  plotter:
    - class_name: mlwiz.training.callback.plotter.WidthPlotter
      args:
        store_on_disk: true
        store_every_N_steps: 1
