defaults:
  - dataset: mnist
  - resources: ddp
  - reproducibility: default
  - data_loading: torch
  - experiment: default
  - _self_

experiment:
  exp_name: mlp_ddp
  model_selection_training_runs: 2

grid:
  defaults:
    - optimizer: adam_001
    - search/mlp@_here_
    - _self_
  model: mlwiz.model.MLP
  checkpoint: true
  shuffle: true
  batch_size: 512
  epochs: 10
  dim_embedding: 5
  mlwiz_tests: true
