defaults:
  - dataset: mnist
  - resources: cpu
  - reproducibility: default
  - data_loading: torch
  - experiment: default
  - _self_

resources:
  max_cpus: 64

experiment:
  exp_name: mlp_bayes
  model_selection_training_runs: 2

bayes:
  defaults:
    - optimizer: bayes_adam
    - search/bayes_mlp@_here_
    - _self_
  budget: 10
  random_starts: 2
  candidate_pool_size: 64
  ei_xi: 0.001
  model: mlwiz.model.MLP
  checkpoint: true
  shuffle: true
  batch_size:
    sample_method: mlwiz.evaluation.util.choice
    args:
      - 256
      - 512
  epochs: 10
  dim_embedding:
    sample_method: mlwiz.evaluation.util.randint
    args:
      - 16
      - 128
  mlwiz_tests: true
