defaults:
  - dataset: cora
  - resources: cpu
  - reproducibility: default
  - data_loading: pyg
  - experiment: default
  - _self_

experiment:
  exp_name: dgn_single_graph

grid:
  defaults:
    - optimizer: adam_001
    - search/single_graph@_here_
    - _self_
  model: mlwiz.model.DGN
  checkpoint: true
  shuffle: true
  batch_size: 1
  epochs: 2
  dim_embedding: 5
  num_layers: 2
  is_graph_classification: false
  is_single_graph: true
