# EVALUATOR - PROGRESS MANAGER
START_CONFIG = "START_CONFIG"
BATCH = "batch"
BATCH_PROGRESS = "batch_progress"
TOTAL_BATCHES = "total_batches"
END_CONFIG = "end_config"
END_FINAL_RUN = "end_final_run"
RUN_PROGRESS = "run_progress"
RUN_COMPLETED = "run_completed"
RUN_FAILED = "run_failed"
OUTER_FOLD = "outer_fold"
INNER_FOLD = "inner_fold"
CONFIG_ID = "config_id"
RUN_ID = "run_id"
ELAPSED = "elapsed"
TOTAL_EPOCHS = "total_epochs"
IS_FINAL = "is_final"
EXP_NAME = "exp_name"
SEED = "seed"
EXPERIMENT_LOGFILE = "experiment.log"
GRID_SEARCH = "grid"
RANDOM_SEARCH = "random"
NUM_SAMPLES = "num_samples"
SAMPLE_METHOD = "sample_method"
DATASET = "dataset"
CONFIG = "config"
MODEL_ASSESSMENT = "MODEL_ASSESSMENT"
FOLDS = "folds"
TR_LOSS = "training_loss"
VL_LOSS = "validation_loss"
TR_SCORE = "training_score"
VL_SCORE = "validation_score"
BEST_CONFIG = "best_config"
OUTER_TRAIN = "outer_train"
OUTER_VALIDATION = "outer_validation"
OUTER_TEST = "outer_test"
TRAINING_TIME_SECONDS = "training_timeout_seconds"

# SPLITTER
DATA_SPLITTER_BASE_PATH = "mlwiz.data.splitter."

# ENGINE
DEFAULT_ENGINE_CALLBACK = (
    "mlwiz.training.callback.engine_callback.EngineCallback"
)

# STATE
MODE = "mode"
TRAINING = "training"
EVALUATION = "evaluation"
VALIDATION = "validation"
TEST = "test"
MAIN_LOSS = "main_loss"
MAIN_SCORE = "main_score"
LOSSES = "losses"
LOSS = "loss"
SCORES = "scores"
SCORE = "score"
MODEL_STATE = "model_state"
OPTIMIZER_STATE = "optimizer_state"
SCHEDULER_STATE = "scheduler_state"
BEST_EPOCH = "best_epoch"
BEST_EPOCH_RESULTS = "best_epoch_results"
EPOCH = "epoch"
LAST_RUN_ELAPSED_TIME = "last_run_elapsed_time"
STOP_TRAINING = "stop_training"
LAST_CHECKPOINT_FILENAME = "last_checkpoint.pth"
BEST_CHECKPOINT_FILENAME = "best_checkpoint.pth"
BATCH_LOSS_EXTRA = "batch_loss_extra"

# STRING FORMATTING
TENSORBOARD = "tensorboard"
EMB_TUPLE_SUBSTR = "_embeddings_tuple"
ATOMIC_SAVE_EXTENSION = ".part"
CLASS_NAME = "class_name"
ARGS = "args"
MODEL_STATE_DICT = "model_state_dict"
OPTIMIZER_STATE_DICT = "optimizer_state_dict"
AVG = "avg"
STD = "std"
CI = "ci"
READOUT = "readout"

# SET UP
CUDA = "cuda"
MLWIZ_RAY_NUM_GPUS_PER_TASK = "MLWIZ_RAY_NUM_GPUS_PER_TASK"
MIN = "min"
MAX = "max"

# CLI
CONFIG_FILE_CLI_ARGUMENT = "--config-file"
CONFIG_FILE = "config_file"
DEBUG_CLI_ARGUMENT = "--debug"
EXECUTE_CONFIG_ID_CLI_ARGUMENT = "--execute-config-id"
SKIP_SPLITS_CHECK_CLI_ARGUMENT = "--skip-data-splits-check"
SKIP_CONFIG_IDS_CLI_ARGUMENT = "--skip-config-ids"
TIME_DELTA = 2.0  # MIN time that needs to pass between two batches or epochs to notify the ProgressManager
CUMULATIVE_UNSENT_DELTA = 10.0  # MAX time that needs to pass between two batches or epochs to notify the ProgressManager

DATA_SPLITS_FILE = "data_splits_file"
SKIP_SPLITS_CHECK = "skip_splits_check"
DATASET_CLASS = "dataset_class"
DATASET_GETTER = "dataset_getter"
evaluate_every = "evaluate_every"
EVALUATE_EVERY = "evaluate_every"
DATA_LOADER = "data_loader"
DATA_LOADER_ARGS = "data_loader_args"
DATASET_NAME = "dataset_name"
STORAGE_FOLDER = "storage_folder"
DEBUG = "debug"
DEVICE = "device"
EXECUTE_CONFIG_ID = "execute_config_id"
SKIP_CONFIG_IDS = "skip_config_ids"
EXPERIMENT = "experiment"
RISK_ASSESSMENT_TRAINING_RUNS = "risk_assessment_training_runs"
MODEL_SELECTION_TRAINING_RUNS = "model_selection_training_runs"
GPUS_PER_TASK = "gpus_per_task"
HIGHER_RESULTS_ARE_BETTER = "higher_results_are_better"
MAX_CPUS = "max_cpus"
MAX_GPUS = "max_gpus"
GPUS_SUBSET = "gpus_subset"
MODEL = "model"
RESULT_FOLDER = "result_folder"

# TELEGRAM BOT
TELEGRAM_CONFIG_FILE = "telegram_config_file"
TELEGRAM_BOT_TOKEN = "bot_token"
TELEGRAM_BOT_CHAT_ID = "bot_chat_ID"
LOG_MODEL_SELECTION = "log_model_selection"
LOG_FINAL_RUNS = "log_final_runs"
