splitter:
  splits_folder: DATA_SPLITS/
  class_name: mlwiz.data.splitter.SingleGraphSplitter
  args:
    n_outer_folds: 3
    n_inner_folds: 2
    seed: 42
    stratify: True
    shuffle: True
    inner_val_ratio: 0.1  # let's use a portion of the training set for validation at model selection time
    outer_val_ratio: 0.1  # let's use a portion of the training set for validation at risk assessment time
    test_ratio: 0.1  # not used in this case
dataset:
  class_name: mlwiz.data.dataset.Cora
  args:
    storage_folder: DATA/